#!/bin/bash

# journey
#
# A script for managing a text file-based journal
#
# Written by Noah Dominic Miranda Silvio
# Copyright (c) 2022 - 2023 Noah Dominic Miranda Silvio.
# All rights reserved.
#

print_manual() {
    echo "JOURNEY"
    echo
    echo "NAME"
    echo "       journey - A script for managing a text file-based journal"
    echo
    echo "SYNOPSIS"
    echo "       journey <command>"
    echo
    echo "DESCRIPTION"
    echo "       The is a bash script for managing a journal.   It provides various"
    echo "       commands for different journal operations. "
    echo
    echo "COMMANDS"
    echo "       The following commands are supported by the Journey script:"
    echo
    echo "       init   Initialises the Journey base folder."
    echo
    echo "       new    Initializes a new journal entry for the current day and opens it"
    echo "              in the default editor (Vim).  This may be changed by editing "
    echo "              the \`\$EDITOR\` variable in the script."
    echo
    echo "       show   Displays the contents of the current day's journal entry using"
    echo "              the 'less' pager."
    echo
    echo "       write  Opens the current day's journal entry in the default editor"
    echo "              (Vim) for writing or editing."
    echo
    echo "       vim    Opens the current day's journal entry in Vim for writing or"
    echo "              editing."
    echo
    echo "       nano   Opens the current day's journal entry in the Nano editor for"
    echo "              writing or editing."
    echo
    echo "       *      If an unrecognized command is provided, the script will display"
    echo "              a default message."
    echo
    echo "AUTHOR"
    echo "       Written by Noah Dominic Miranda Silvio"
    echo
    echo "COPYRIGHT"
    echo "       This is software is released under the EU Public Licence v. 2.0"
    echo
    echo "BUGS"
    echo "       Please report any bugs or issues to \`noah@noahdominic.com\`."
}

JOURNEY_BASEPATH="$HOME/journey"
TODAY=$(date +'%Y/%m/%d')
TODAYS_ENTRY="$JOURNEY_BASEPATH/$TODAY"
EDITOR="vim"

write() {
    eval "$EDITOR" + "$TODAYS_ENTRY"
}

# Main command dispatcher
case "$1" in
    init)
        mkdir -p "$JOURNEY_BASEPATH"
        ;;
    new)
        inittoday
        write
        ;;
    show)
        less "$TODAYS_ENTRY"
        ;;
    write)
        write
        ;;
    vim)
        vim "$TODAYS_ENTRY"
        ;;
    nano)
        nano "$TODAYS_ENTRY"
        ;;
    -h) 
        print_manual | less
        ;;
    *)
        echo "usage: journal command"
        ;;
esac
