#!/bin/sh

# Check if 7z is installed
if ! command -v 7z &> /dev/null; then
    echo "7z command not found.  Please install 7zip package for Linux from the official website (https://www.7-zip.org/download.html)."
    exit 1
fi

extension="$1"

if [ -z "$extension" ]; then
    echo "Usage: $0 <extension>"
    exit 1
fi

for file in *."$extension"; do
    foldername=$(basename -s ".$extension" "$file")
    mkdir -p "$foldername" && 7z x "$file" -o"$foldername"
done

