#!/bin/sh
 
# Check if git is installed
if ! command -v git &> /dev/null; then
    echo "git not found.  Please install git from your OS's repositories."
    exit 1
fi

if [ $# -eq 0 ]; then
        echo "git rebaseall - Rebase multiple branches into the current branch"
        echo "Usage: git rebaseall branch 1 [branch2 ...]"
        exit 1
fi

current_branch=$(git rev-parse --abbrev-ref HEAD)

for branch in "$@"; do
        echo "Rebasing branch '$branch' into '$current_branch'"
        git checkout "$branch" && git rebase "$current_branch"
done

git checkout "$current_branch"
