#!/bin/sh

# NOTE: macOS has their own `mkfile`.  Its API is different than this one.
# This `mkfile` is more of an extended/limited version of `touch`
# in the sense that it only make empty files, but it can also
# accept pathed filenames.

if [ $# -le 2 ]; then
	echo "Usage: mkfile <path/to/file.extension>"
	exit 1
fi

for file in "$@"; do
	mkdir -p "$(dirname "$file")" && touch "$file"
done
