#!/bin/sh

# Check if git is installed
if ! command -v ffmpeg &> /dev/null; then
  echo "ffmpeg not found.  Please install ffmpeg from your OS's repositories."
  exit 1
fi

mkdir -p ts

for file in *.ts
do
  base="${file%.ts}"
  ffmpeg -y -i "$file" -vcodec copy -acodec copy -map 0:v -map 0:a "$base.mp4"
  mv "$file" ts/
done

